title: "Resque: a job queue"
email: steve@steveklabnik.com
description: >
  Resque is a Redis-backed Ruby library for creating background jobs, placing
  them on multiple queues, and processing them later.
url: "http://resque.github.io"

# Build settings
markdown: kramdown
